### ISSUE TITLE
cx-Freeze is saying there's a Python error in on startup

### ISSUE THREAD

**Issue by nuclearflame11** [DRGN-DRC/DAT-Texture-Wizard#2]
So whenever I start up "DAT Texture Wizard.exe" I get this error
![image](https://user-images.githubusercontent.com/46734887/107164655-9366a580-6975-11eb-9053-a3657864326c.png)
I believe I have properly installed Python 2.7.18, along with cx-Freeze 5.1.1, psutil, and Pillow all for Python 2.7. I believe that this might mean that there are extra characters after a certain line?
I am running this on a Windows 10 64-bit computer.
edit: I'm using v6.1.2

**Comment by DRGN-DRC** [comment]
Hm. Sorry, I'm not familiar with this error.

Is this the 6.1.2 build downloaded from releases, or is this a build you compiled from the source code? Do be clear, you don't need to install Python or anything else if you're just trying to run one of the pre-compiled builds.

Does it run uncompiled? To run the source code (uncompiled), you should be able to just double-click on the "DAT Texture Wizard Debug.bat" file. Also, it might be worth asking, what's the path of the root directory (that the main "DAT Texture Wizard.py" script is in)?

I'm currently using Python v2.7.16, but I'm pretty sure I've run it with newer versions as well. I'll try to confirm this in a few days.

**Comment by DRGN-DRC** [comment]
I just tried the source code on another system, and it's working with Python 2.7.18 as well (on Windows 10, x64, build 18363). Building a new exe and running that also worked.

The error happens when attempting to add the library directory for drag-and-drop functionality to Tcl's "auto_path" global variable. I'm not sure this will help, but since it seems like it might be a strange syntax issue, you might try writing line 21 in newTkDnD.py a different way; perhaps instead of:
`"master.tk.eval('global auto_path; lappend auto_path {%s}' % tkdndlib)"`
maybe:
`"master.tk.eval( 'global auto_path; lappend auto_path {{}}'.format(tkdndlib) )"`

But it might be [more likely] that somehow an invalid path is being provided. You could see what's being provided by using a debugger or adding a print statement for the tkdndlib variable right before the above line (e.g. `print 'attempting to add path', tkdndlib`). You could also see what is in the auto_path list by adding `master.tk.eval('global auto_path; puts $auto_path')`. Alternatively, if you don't care about drag-and-drop functionality, you could comment out the lines related to it in the main script.

**Comment by nuclearflame11** [comment]
Ok, so I looked back at the directory as you said in the first comment, and I noticed that the directory might have either been too long or it had characters such as ~ or {}. After putting it in a higher-up directory that doesn't have these symbols it worked. Interesting. So the directory path was the problem.
